# Generated by Django 5.0 on 2024-11-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
